moveit_sim_hw_interface:
  joint_model_group: antonie_arm
  joint_model_group_pose: home
# MoveIt controllers to load
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_controllers:
  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gripper_1_joint
      - gripper_2_joint
